name: CI Soft

on:
  push:
    branches-ignore:
      - main
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt flake8 pytest-cov
      - name: Lint
        run: flake8 src tests --max-line-length=120 --extend-ignore=E402
      - name: Test
        run: pytest
